name: Build Python Executable for Linux

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up linux environment
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y python3 python3-pip python3-venv binutils

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller xml2st.py --add-data plcopen:plcopen

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: dist/xml2st
